# Generated by Django 3.1 on 2022-05-11 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_tempo_precentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PracticeCellCompletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composer', models.CharField(max_length=255)),
                ('part', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_tempo', models.IntegerField()),
                ('start_measure', models.CharField(max_length=25)),
                ('end_measure', models.CharField(max_length=25)),
                ('steps', models.IntegerField()),
                ('practice_cells', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perform.practicecell')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeGrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_rows', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perform.practicerow')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perform.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perform.user')),
            ],
        ),
        migrations.AddField(
            model_name='practicecell',
            name='practice_cell_completions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perform.practicecellcompletion'),
        ),
    ]
