# Generated by Django 3.1 on 2020-08-08 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0002_auto_20200808_0008'),
        ('perform', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Performer',
        ),
    ]
