# Generated by Django 3.1 on 2022-05-14 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perform', '0002_auto_20220514_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicecell',
            name='practice_cell_completions',
        ),
        migrations.RemoveField(
            model_name='practicegrid',
            name='practice_rows',
        ),
        migrations.RemoveField(
            model_name='practicerow',
            name='practice_cells',
        ),
        migrations.AddField(
            model_name='practicecell',
            name='practice_row',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='perform.practicerow'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practicecellcompletion',
            name='practice_cell',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='perform.practicecell'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practicegrid',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='practicegrid',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practicerow',
            name='practice_grid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='perform.practicegrid'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='practicegrid',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perform.song'),
        ),
        migrations.AlterField(
            model_name='practicegrid',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perform.user'),
        ),
    ]
