# Generated by Django 3.1 on 2022-05-17 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perform', '0003_auto_20220514_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practicecell',
            old_name='target_tempo_precentage',
            new_name='target_tempo_percentage',
        ),
    ]
