# Generated by Django 3.1 on 2022-05-17 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perform', '0004_auto_20220517_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicegrid',
            name='song',
        ),
        migrations.AddField(
            model_name='practicerow',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perform.song'),
        ),
        migrations.AddField(
            model_name='song',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='composer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='part',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
