# Generated by Django 3.1 on 2022-05-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perform', '0005_auto_20220517_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicecellcompletion',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
