# Generated by Django 3.1 on 2022-06-07 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perform', '0006_auto_20220517_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicegrid',
            name='user',
        ),
        migrations.AlterField(
            model_name='practicerow',
            name='practice_grid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_rows', to='perform.practicegrid'),
        ),
    ]
