# Generated by Django 2.2 on 2019-05-18 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ensemble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='direct.Director')),
            ],
        ),
        migrations.CreateModel(
            name='EnsembleMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ensemble', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='direct.Ensemble')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='perform.Performer')),
            ],
        ),
    ]
