# Generated by Django 3.1 on 2020-08-08 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ensemble',
            name='director',
        ),
        migrations.RemoveField(
            model_name='ensemblemember',
            name='ensemble',
        ),
        migrations.RemoveField(
            model_name='ensemblemember',
            name='performer',
        ),
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.DeleteModel(
            name='Ensemble',
        ),
        migrations.DeleteModel(
            name='EnsembleMember',
        ),
    ]
