# Generated by Django 3.1 on 2020-08-10 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ensemble',
            old_name='Address',
            new_name='address',
        ),
    ]
